environment: ubuntu2204-docker
modes:
  default: [default]
build:
  - set -o pipefail
  - apt-get -qqy update
  - apt-get -qqy install curl protobuf-compiler libprotobuf-dev musl-tools
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - /root/.cargo/bin/rustup target add x86_64-unknown-linux-musl
  - /root/.cargo/bin/cargo install cargo-outdated
  - /root/.cargo/bin/cargo outdated --depth 1 --exit-code 1
  - /root/.cargo/bin/cargo build --release --target x86_64-unknown-linux-musl
  - docker-compose -f docker-compose-cicd.yml up --build --abort-on-container-exit --force-recreate --no-color 2>&1 | grep ^tester_
  - mkdir build
  - strip target/x86_64-unknown-linux-musl/release/stilgar
  - mv target/x86_64-unknown-linux-musl/release/stilgar deploy.sh build
  - tar -czf stilgar.tar.gz build/
publish: stilgar.tar.gz
