stages:
  - test
  - build

default:
  image: ubuntu:20.04
  before_script:
    - apt update
    - apt install -y musl-tools
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - /root/.cargo/bin/rustup target add x86_64-unknown-linux-musl

tests:
  stage: test
  script:
    - /bin/true  # TODO: test the thing

build:
  stage: build
  script:
    - /root/.cargo/bin/cargo build --release --target x86_64-unknown-linux-musl
    - mkdir build
    - mv target/x86_64-unknown-linux-musl/release/stilgar build
    - tar czf stilgar.tar.gz build/
  artifacts:
    paths:
      - stilgar.tar.gz
    expire_in: 1 day
