version: '3'
services:

  beanstalkd:
    extends:
      file: docker-compose.yml
      service: beanstalkd

  clickhouse:
    extends:
      file: docker-compose.yml
      service: clickhouse

  stilgar:
    build:
      context: .
      dockerfile: Dockerfile.cicd
    volumes:
      - ./target/x86_64-unknown-linux-musl/release/stilgar:/bin/stilgar
      - ./stilgar.dev.yml:/etc/stilgar.yml
    command: "bash -c 'while ! nc -z clickhouse 9100; do sleep 1; done; /bin/stilgar /etc/stilgar.yml'"

  tester:
    hostname: tester
    build: test/tester
    depends_on:
      - stilgar
      - beanstalkd
      - clickhouse

volumes:
  clickhouse_data:
