version: '3'
services:

  stilgar:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - .:/home/stilgar
    ports:
      - 8081:8080
    environment:
      - "STILGAR_CONFIG=stilgar.dev.yml"

  clickhouse:
    build: test/clickhouse
    tty: true
    environment:
      - CLICKHOUSE_USER=myuser
      - CLICKHOUSE_PASSWORD=mypassword
      - CLICKHOUSE_DB=mydatabase
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - ./test/clickhouse/conf.d:/etc/clickhouse-server/conf.d
    expose:
      - 8123
      - 9000
    ports:
      - 8123:8123
      - 9000:9000

  js:
    image: python:3
    tty: true
    volumes:
      - ./test/js:/home/js
    working_dir: /home/js
    command: python3 -m http.server
    ports:
      - 8082:8000

  tester:
    hostname: tester
    build: test/tester
    tty: true
    profiles:
      - donotstart
    volumes:
      - ./test/tester:/home/tester/tester
    depends_on:
      - stilgar
      - clickhouse

volumes:
  clickhouse_data:
